# Generated by Django 2.1.1 on 2018-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scse_cz3003_2018_s1_cms_app', '0002_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicserviceannouncement',
            name='publish',
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
