# Generated by Django 2.1.2 on 2018-10-17 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scse_cz3003_2018_s1_cms_app', '0004_auto_20181001_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('mobile_number', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('postal_code', models.CharField(max_length=128)),
                ('unit_number', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('validated', models.CharField(default='unseen', max_length=128)),
                ('crisis_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scse_cz3003_2018_s1_cms_app.CrisisLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('incident_report', models.ManyToManyField(to='scse_cz3003_2018_s1_cms_app.IncidentReport')),
            ],
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scse_cz3003_2018_s1_cms_app.Source'),
        ),
    ]
