# Generated by Django 2.1.1 on 2018-10-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scse_cz3003_2018_s1_cms_app', '0005_auto_20181017_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('national', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('north', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('south', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('east', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('west', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('central', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('type', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PsiType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_readable_name', models.CharField(max_length=128)),
                ('machine_readable_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
