# Generated by Django 2.1.1 on 2018-10-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scse_cz3003_2018_s1_cms_app', '0007_auto_20181025_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psi',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='psitype',
            name='machine_readable_name',
            field=models.CharField(max_length=128),
        ),
    ]
