# Generated by Django 2.1.1 on 2018-10-25 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scse_cz3003_2018_s1_cms_app', '0008_auto_20181025_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psi',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scse_cz3003_2018_s1_cms_app.PsiType'),
        ),
    ]
