# Generated by Django 2.1.2 on 2018-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20181007_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='validated',
            field=models.CharField(default='unseen', max_length=128),
        ),
    ]
